### ISSUE TITLE
a few questions for frugalos

### ISSUE THREAD

**Issue by thesues** [frugalos/frugalos#164]
hi, list,
 I am reading the code of frugalos, but I have the following questions.
1. It seems frugalos doesn't use raft to replicate the data, why?
2. what's the relationship between "node" and "segment"?

**Comment by shinnya** [comment]
Hi.

> 1. It seems frugalos doesn't use raft to replicate the data, why?

No. We use Raft as a consensus algorithm to manage the index of registered objects. The implementation of the algorithm is at https://github.com/frugalos/raftlog.

For instance, you can find an example of use of Raft at https://github.com/frugalos/frugalos/blob/c56b048d94fd2651c218ff43344e4f8a2da5b06d/frugalos_mds/src/node/node.rs#L871. (`rlog` is `ReplicatedLog` in `raftlog`)


> 2. what's the relationship between "node" and "segment"?

A `segment` is correspond to a Raft cluster, so the relationship is that a `segment` consists of multiple `node`s(may be distributed across multiple servers if you create a frugalos cluster). frugalos creates a `node`(or multiple `node`s) and places it on each `segment`. The created `node` is something like a light weight process in Erlang. A `segment` manages a subset of entire objects and it's same as `node`  because you can substantially regard `node` as `segment`.



Note 1: A `Segment` is conceptually one of the partitioned range of `ObjectId`. There is no concrete object. When you put a new object into frugalos, frugalos computes the hash value of the id of the object and chooses an appropriate segment of the object. `Segment` manages one fixed range of an entire object namespace. `Segment`s are created statically and never change(so far) when you create a new `Bucket` on frugalos.


Note 2: The word `node` is a bit confusing because there is two types of `node`. The first is `frugalos_mds::Node` and the second is `frugalos_segment::SegmentNode`.

frugalos runs one `frugalos_segment::SegmentNode`(i.e., a member of Raft consensus algorithm) for each `segment`(strictly speaking, it's not always true), so we call `node` as `SegmentNode`. You can find it at https://github.com/frugalos/frugalos/blob/c56b048d94fd2651c218ff43344e4f8a2da5b06d/frugalos_segment/src/service.rs#L197.

**Comment by thesues** [comment]
Thank for your detailed answer. it really helps.

Do you have any plan to write a more detailed wiki for  frugalos, just like what you did in Cannyls' wiki?

**Comment by shinnya** [comment]
No, I won't in the near future but other members might do.
